AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: The Anonymous Wall - Serverless Anonymous Message Board

Globals:
  Function:
    Timeout: 10
    Runtime: python3.12
    MemorySize: 128

Resources:

  MessagesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Messages
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  MessageIndexTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: MessageIndex
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  RateLimitTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: RateLimit
      AttributeDefinitions:
        - AttributeName: ip
          AttributeType: S
      KeySchema:
        - AttributeName: ip
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true

  SubmitMessageFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: SubmitMessage
      CodeUri: backend/submit_message/
      Handler: app.lambda_handler
      Policies:
        - AmazonDynamoDBFullAccess
      Events:
        SubmitAPI:
          Type: HttpApi
          Properties:
            Path: /submit
            Method: POST

  GetRandomMessageFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: GetRandomMessage
      CodeUri: backend/get_random_message/
      Handler: app.lambda_handler
      Policies:
        - AmazonDynamoDBFullAccess
      Events:
        GetAPI:
          Type: HttpApi
          Properties:
            Path: /random
            Method: GET

  CleanupRemovedMessagesFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: CleanupRemovedMessages
      CodeUri: backend/cleanup_removed/
      Handler: app.lambda_handler
      Policies:
        - AmazonDynamoDBFullAccess
      Events:
        DailyCleanupTrigger:
          Type: Schedule
          Properties:
            Schedule: cron(0 4 * * ? *)  # Runs every day at 4 AM UTC
